[package]
name = "evm-state-chain-spec"
version = "0.1.0"
edition.workspace = true

[dependencies]
evm-state-data-types = { workspace = true }
alloy-primitives = { workspace = true }
revm = { workspace = true }
